name: 'Surefire Report'
description: 'Report Surefire test results as annotations on Github Pull Request'
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report_paths:
    description: 'surefire xml report paths in glob format'
    required: false
    default: '**/surefire-reports/TEST-*.xml'
  check_name:
    description: 'check name for test reports'
    required: false
    default: 'Test Report'
runs:
  using: 'node12'
  main: 'dist/index.js'
