name: build-2
on:
  pull_request:

concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-main-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-main-maven-
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - run: cd tests && mvn clean test --batch-mode -Dmaven.test.failure.ignore=true
      - uses: ./
        if: github.ref != 'refs/heads/master'
        with:
          check_name: Example Surefire Test Report
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: java-reports
          path: |
            **/surefire-reports/TEST-*.xml
            **/failsafe-reports/TEST-*.xml
      

